package aplicacion;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import conexiones.OracleConnection;

public class Libros {
    int idLibro;
    String isbn;
    String titulo;
    String autor;
    int anho;
    boolean disponible;
    byte[] portada; // equivalente a binary no deja de ser un array de bytes como una foto

    public void crearTabla() {
        try (Connection conn = new OracleConnection().getConnection();
                Statement acciones = conn.createStatement()) {
            // oracle sql syntax
            String sql = "CREATE TABLE libros (" +
                    "idLibro NUMBER GENERATED BY DEFAULT AS IDENTITY," +
                    "isbn VARCHAR2(13) UNIQUE NOT NULL," +
                    "titulo VARCHAR2(255) NOT NULL," +
                    "autor VARCHAR2(255) NOT NULL," +
                    "anho NUMBER(4) NOT NULL," +
                    "disponible NUMBER(1)," +
                    "portada BLOB, " +
                    "CONSTRAINT BOOK_PK PRIMARY KEY (idLibro)" +
                    ")";
            acciones.execute(sql);
            System.out.println("Tabla libros creada correctamente.");
        } catch (SQLException e) {
            System.out.println("Error de sintaxis en la tabla libros:");
            System.out.println(e.getMessage());
            System.out.println(e.getCause());

        } catch (Exception e) {
            System.out.println("Error desconocido creando la tabla libros:");
            System.out.println(e.getMessage());
            System.out.println(e.getCause());
        }
    }
}
